### ISSUE TITLE
RSB eth_getLogs requests out of control

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden-service-bundle#166]
# Problem Description
I just got an email from the infura team pointing out that my account has 2million to 2.5
million requests per day.

I use infura for the testenv001 RSB that the light client team uses atm.

Based on my 30-day Dashboard the amount of `eth_getLogs` requests seem to be completely out of control. (~2 million req per day)
![image](https://user-images.githubusercontent.com/3756671/83499335-8546b800-a4bd-11ea-8b52-1aa12e789c06.png)

**Comment by palango** [comment]
Which network is that? And do you know how many token networks are registered on that one?

**Comment by eorituz** [comment]
It runs on the goerli network.
Here is my `.env` file
```

**Comment by eorituz** [comment]
The amount of token networks seems to be quite high, yes.

```

**Comment by palango** [comment]
@eorituz I fixed that problem in https://github.com/raiden-network/raiden-services/pull/793

I guess you cannot update that RSB yet, but I can create an services release for you whenever it fits you.

**Comment by palango** [comment]
@eorituz The fix is in the latest release (https://github.com/raiden-network/raiden-services/releases/tag/v0.11.0)

**Comment by palango** [comment]
Fixed in https://github.com/raiden-network/raiden-services/pull/793
