### ISSUE TITLE
RSB Installed

### ISSUE THREAD

**Issue by hymner** [raiden-network/raiden-service-bundle#168]
SERVER_NAME=raiden.overdoze.se

2020-06-02 18:40:07.102859 [info     ] Updated infos                  [__main__] current_url=https://pfs.raiden.overdoze.se

**Comment by palango** [comment]
Thanks for the PR. The PFS doesn't seem to be up, have you checked the logs? 

https://pfs.raiden.overdoze.se/api/v1/info should return some infos.

**Comment by hymner** [comment]
Hey!

Yeah apparantly i hadn’t fully started the docker container :)

How does it look now ?

Mvh / Best Regards

Gilbert

Från: Paul Lange <notifications@github.com>
Skickat: den 3 juni 2020 09:14
Till: raiden-network/raiden-service-bundle <raiden-service-bundle@noreply.github.com>
Kopia: hymner <gilbert@overdoze.se>; Author <author@noreply.github.com>
Ämne: Re: [raiden-network/raiden-service-bundle] RSB Installed (#168)

Thanks for the PR. The PFS doesn't seem to be up, have you checked the logs?

https://pfs.raiden.overdoze.se/api/v1/info should return some infos.

**Comment by palango** [comment]
The PFS still seems to be down. Can you check the logs again?

**Comment by fredo** [comment]
Please note that it can take up to 24 hours until the rest of the federation integrated the new member. In this time the PFS could still be down. Please, check again tomorrow afternoon

**Comment by palango** [comment]
@hymner The PFS is still not online. Can you have a look at the logs please?

@fredo This shouldn't be federation related any more, right?

**Comment by hymner** [comment]
@palango raiden-service-bundle_msrc_1 , raiden-service-bundle_pfs_1 , raiden-service-bundle_room_ensurer_1 seems to repeatedly restart, which logs specifically do you want ?

**Comment by palango** [comment]
Sounds like `raiden-service-bundle_room_ensurer_1` could be the problem. Can you provide those logs first?
@fredo thoughts?

**Comment by hymner** [comment]
https://pastebin.com/B6Mg3RRu

**Comment by palango** [comment]
@hymner Thanks for the logs. 
The problem seems to stem from your `.env` file. In line 32 it defines `URL_KNOWN_FEDERATION_SERVERS`, which is a setting only for testing. It isn't necessary to define it. Can you comment it out and restart the services?

**Comment by hymner** [comment]
@palango yeah i was unsure about that one, thanks for the info. It's now been commented out and box is restarted. Seems like i'm getting the same error though:

Log from raiden-service-bundle_room_ensurer_1 : https://pastebin.com/9dzVxxQy

**Comment by palango** [comment]
That's weird...
Can you search in the directory for `/known_servers/known_servers.alder` and see if there's any other location were it might have ended up?

Otherwise, you did `docker-compose down && docker up -d` again?

**Comment by hymner** [comment]
docker noob <- thats me! :)

docker-compose down / docker-compose up -d worked like a charm, getting much more logs now.

**Comment by palango** [comment]
@hymner That looks much better now. Seems like the rooms haven't been created yet. Can you giuve me the logs for `raiden-service-bundle_room_ensurer_1` as well?

**Comment by hymner** [comment]
@palango sure thing: https://pastebin.com/BXv3Qv0h

**Comment by palango** [comment]
@hymner There seem to be some lines from the traceback mssing. Can you please check again.

Also, do you want to join gitter, then we can talk directly: https://gitter.im/raiden-network/raiden

**Comment by palango** [comment]
@hymner We released a new version with a fix. Can you please install that as of https://github.com/raiden-network/raiden-service-bundle#upgrades

Thanks a lot!

**Comment by hymner** [comment]
@palango I did the upgrade per instructions, also updated the .env with the new metrics whitelist / proxy whitelist IP.

raiden-service-bundle_msrc_1 and raiden-service-bundle_pfs_1 keeps restarting now, let me know if you need fresh logs!

**Comment by palango** [comment]
@hymner Thanks. Let's wait until tomorrow as the federation might take some time.

**Comment by hymner** [comment]
Ok, no problem, let's see tomorrow :)

**Comment by palango** [comment]
@hymner There's one more RSB to be updated. The error is thrown because your matrix server is still not excepted there. We pinged the provider and hopefully they update soon.

**Comment by hymner** [comment]
@palango ahh i see! ok, thanks for the info!

**Comment by hymner** [comment]
@palango I guess we're still waiting on DAppNode's RSB to be updated right ? =)

**Comment by palango** [comment]
@hymner Yes, unfortunately I don't have any further information.

**Comment by palango** [comment]
@hymner The last RSB is updated. Can you try restarting your RSB, `docker-compose down` and then `docker-compose up -d`

**Comment by hymner** [comment]
@palango cool! Ok RSB has been restarted.

**Comment by hymner** [comment]
Hey @ulope 

Ok, no problem, but could you be more specific on exactly what file(s) that needs to be deleted, just so i don't delete anything i shouldn't :) My data dir is the default. I See a bunch of files under data/db , but nothing related to checkout.

**Comment by ulope** [comment]
There isn't really anything in the data directory that would hurt (since the entire setup is designed to be able to cope with empty initial state).

In this specific case you can just delete the entire `db` directory inside `data`.

**Comment by hymner** [comment]
Thanks for the clarification @ulope :) It's now been deleted and RSB is started again

**Comment by hymner** [comment]
This is what happens with the pfs service now: https://pastebin.com/wZqw3nXN
Do we need to wait 24h ?

**Comment by ulope** [comment]
No the rooms should be created relatively quickly. Can you post the log of the `room_ensurer`?

**Comment by hymner** [comment]
https://pastebin.com/sji4rkJ8 heading out for a couple of hours but please let me know if you need anything else!

**Comment by ulope** [comment]
@hymner Do you have time to have a quick chat in gitter at some point? That will probably be a faster way to solve this.

**Comment by hymner** [comment]
@ulope no problem, i have time now!

**Comment by ulope** [comment]
I'd be available in ~30 minutes does that still work for you?

**Comment by hymner** [comment]
That works, just hit me up on gitter :)

**Comment by hymner** [comment]
@Dominik1999 I do believe @ulope is still working on this, RSB is still not running as it should.

**Comment by Dominik1999** [comment]
ah I am sorry. I will check

**Comment by hymner** [comment]
hehe no worries :) It's been on the backburner because of Raiddit of course :)

**Comment by karlb** [comment]
This is currently blocked by https://github.com/raiden-network/raiden-service-bundle/issues/180.

**Comment by hymner** [comment]
I suspected as much, thanks for the info @karlb

**Comment by hymner** [comment]
Alright friends, updated to 2020.10.3 and things looks better to me :) 
@ulope If you can take a look that's everything ok when you have the time, i'd be a happy camper!
Great work you guys.

**Comment by fredo** [comment]
@ulope is this done?

**Comment by ulope** [comment]
All the things are working 🎉
