### ISSUE TITLE
Upgrade Synapse to 1.19.1

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-service-bundle#180]
# Problem Description

We're still using Synapse `1.10.1`. 
There have been a lot of bug / security fixes since then.

Most urgently this is needed because there's a bug in applying retention policies in `1.10.1` (https://github.com/matrix-org/synapse/issues/6713) which currently makes the databases grow boundlessly on our test servers.

The impact of the following changes need to be evaluated before we can perform the upgrade:

Backwards compatibility:
- EthAuthProvider:
  - registration handler async: https://github.com/matrix-org/synapse/pull/7649
  - Auth handler async / await: https://github.com/matrix-org/synapse/pull/7261
- Raiden Client:
  - `displayname` and `avatar_url` are no longer sent on `m.room.member` events if they are missing: https://github.com/matrix-org/synapse/pull/7497
  - `publicRooms` endpoint no longer delivers aliases: https://github.com/matrix-org/synapse/pull/6970
  - Alias semantics changes (MSC2432): https://github.com/matrix-org/synapse/issues/6898

Features (can possibly improve performance and / or simplify implementations):
- Admin device API: https://github.com/matrix-org/synapse/pull/7481
- Cache factor config: https://github.com/matrix-org/synapse/pull/6391
- Worker replication can now use Redis: https://github.com/matrix-org/synapse/issues/7040
- Admin users can create room aliases without having to join it: https://github.com/matrix-org/synapse/issues/7191
- Room aliases can be deleted by canonical alias power level users: https://github.com/matrix-org/synapse/issues/6986

**Comment by fredo** [comment]
do we actually use the endpoint `publicRooms`?
