### ISSUE TITLE
 inclusion in the list of known servers

### ISSUE THREAD

**Issue by mossimokim** [raiden-network/raiden-service-bundle#226]
Just finished registering as a RSB provider. Would you whitelist my server?

Server_Name=raijin1.raiden.ninja

**Comment by ezdac** [comment]
Thank you a lot for your support and dedication. I'm sorry this took so long - this flew under our radar for a while. #230 addresses the initial whitelisting in the Matrix federation.

**Comment by mossimokim** [comment]
I know you guys are busy with release. Please do take time. No rush.

**Comment by ezdac** [comment]
@mossimokim, we noticed that your PFS is still returning a `404`, although we included you in the Matrix federation. Do you need help in troubleshooting the problem?
The last 100 or so lines of your Synapse logs as well as PFS logs would be helpful.

**Comment by mossimokim** [comment]
I will check on it. Thank you finally getting back to me.

**Comment by mossimokim** [comment]
Having issue getting pfs up!

1. raijin1.raiden.ninja is pointed to 159.89.220.153
2. .env file is [here](https://gist.github.com/mossimokim/565b172e1228b3ccc7607a978d79ac61)
3. registered in the registry [here](https://etherscan.io/tx/0x59653c1f3c2da8130e4fd9cda81f48c03ea04bed82475bc47c7838e073791536)
4. matrix endpoint gives HTTP status 200 [here](https://transport.raijin1.raiden.ninja/_matrix/client/versions)
5. pfs is down
6. latest_confirmed_block is increasing regularly
7. msrc & pfs indefinitely restarting


<pre><code>mossimokim@raijin1:~/raiden-service-bundle$ sudo docker-compose ps
[sudo] password for mossimokim:
                    Name                                  Command                  State                        Ports
---------------------------------------------------------------------------------------------------------------------------------------
raiden-service-bundle_db_1                     docker-entrypoint.sh postgres    Up (healthy)   5432/tcp
raiden-service-bundle_federation_sender_1      /bin/synapse-entrypoint.sh ...   Up             8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_1         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_2         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_3         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_4         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_5         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_6         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_7         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_generic_worker_8         /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_metrics_db_1             /postgres_exporter               Up             9187/tcp
raiden-service-bundle_metrics_redis_1          /redis_exporter -redis.add ...   Up             9121/tcp
raiden-service-bundle_ms_1                     python3 -m monitoring_serv ...   Up (healthy)   6000/tcp
raiden-service-bundle_msrc_1                   python3 -m request_collect ...   Restarting
raiden-service-bundle_node_exporter_1          /bin/node_exporter --path. ...   Up             9100/tcp
raiden-service-bundle_pfs_1                    python3 -m pathfinding_ser ...   Restarting
raiden-service-bundle_purger_1                 /purger.sh https://transpo ...   Up             5001/tcp
raiden-service-bundle_redis_1                  docker-entrypoint.sh redis ...   Up (healthy)   6379/tcp
raiden-service-bundle_room_ensurer_1           /opt/venv/bin/python3 /roo ...   Up             5001/tcp
raiden-service-bundle_state_groups_cleaner_1   /state_group_cleaner.sh          Up
raiden-service-bundle_synapse_1                /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_traefik_1                /entrypoint.sh --certifica ...   Up             0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
raiden-service-bundle_user_dir_1               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_2               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_3               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_4               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_5               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_6               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_7               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_user_dir_8               /bin/synapse-entrypoint.sh ...   Up (healthy)   8008/tcp, 9093/tcp, 9101/tcp
raiden-service-bundle_well_known_server_1      nginx -g daemon off;             Up (healthy)   80/tcp</code></pre>

Could not process list of known matrix servers

<pre><code>mossimokim@raijin1:~/raiden-service-bundle/data/keystore$ sudo docker-compose logs --tail 100 room_ensurer
Attaching to raiden-service-bundle_room_ensurer_1
room_ensurer_1          |     known_servers_url, server_list_type=ServerListType.ALL_SERVERS
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 464, in get_matrix_servers
room_ensurer_1          |     ) from ex
room_ensurer_1          | RuntimeError: Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
room_ensurer_1          | 2021-02-23 03:51:15.581349 [debug    ] Starting new HTTPS connection (1): raw.githubusercontent.com:443 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:51:15.612520 [debug    ] https://raw.githubusercontent.com:443 "GET /raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml HTTP/1.1" 200 171 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:51:15.615494 [error    ] Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)') [__main__]
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 457, in get_matrix_servers
room_ensurer_1          |     known_servers: Dict[str, List[str]] = json.loads(response.text)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
room_ensurer_1          |     return _default_decoder.decode(s)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
room_ensurer_1          |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
room_ensurer_1          |     raise JSONDecodeError("Expecting value", s, err.value) from None
room_ensurer_1          | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
room_ensurer_1          |
room_ensurer_1          | The above exception was the direct cause of the following exception:
room_ensurer_1          |
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/room_ensurer.py", line 419, in main
room_ensurer_1          |     room_ensurer = RoomEnsurer(username, password, own_server, known_servers_url)
room_ensurer_1          |   File "/room_ensurer.py", line 99, in __init__
room_ensurer_1          |     known_servers_url, server_list_type=ServerListType.ALL_SERVERS
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 464, in get_matrix_servers
room_ensurer_1          |     ) from ex
room_ensurer_1          | RuntimeError: Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
room_ensurer_1          | 2021-02-23 03:52:15.619750 [debug    ] Starting new HTTPS connection (1): raw.githubusercontent.com:443 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:52:15.765270 [debug    ] https://raw.githubusercontent.com:443 "GET /raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml HTTP/1.1" 200 171 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:52:15.768121 [error    ] Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)') [__main__]
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 457, in get_matrix_servers
room_ensurer_1          |     known_servers: Dict[str, List[str]] = json.loads(response.text)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
room_ensurer_1          |     return _default_decoder.decode(s)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
room_ensurer_1          |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
room_ensurer_1          |     raise JSONDecodeError("Expecting value", s, err.value) from None
room_ensurer_1          | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
room_ensurer_1          |
room_ensurer_1          | The above exception was the direct cause of the following exception:
room_ensurer_1          |
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/room_ensurer.py", line 419, in main
room_ensurer_1          |     room_ensurer = RoomEnsurer(username, password, own_server, known_servers_url)
room_ensurer_1          |   File "/room_ensurer.py", line 99, in __init__
room_ensurer_1          |     known_servers_url, server_list_type=ServerListType.ALL_SERVERS
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 464, in get_matrix_servers
room_ensurer_1          |     ) from ex
room_ensurer_1          | RuntimeError: Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
room_ensurer_1          | 2021-02-23 03:53:15.774322 [debug    ] Starting new HTTPS connection (1): raw.githubusercontent.com:443 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:53:15.830318 [debug    ] https://raw.githubusercontent.com:443 "GET /raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml HTTP/1.1" 200 171 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:53:15.833670 [error    ] Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)') [__main__]
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 457, in get_matrix_servers
room_ensurer_1          |     known_servers: Dict[str, List[str]] = json.loads(response.text)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
room_ensurer_1          |     return _default_decoder.decode(s)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
room_ensurer_1          |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
room_ensurer_1          |     raise JSONDecodeError("Expecting value", s, err.value) from None
room_ensurer_1          | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
room_ensurer_1          |
room_ensurer_1          | The above exception was the direct cause of the following exception:
room_ensurer_1          |
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/room_ensurer.py", line 419, in main
room_ensurer_1          |     room_ensurer = RoomEnsurer(username, password, own_server, known_servers_url)
room_ensurer_1          |   File "/room_ensurer.py", line 99, in __init__
room_ensurer_1          |     known_servers_url, server_list_type=ServerListType.ALL_SERVERS
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 464, in get_matrix_servers
room_ensurer_1          |     ) from ex
room_ensurer_1          | RuntimeError: Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
room_ensurer_1          | 2021-02-23 03:54:15.838756 [debug    ] Starting new HTTPS connection (1): raw.githubusercontent.com:443 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:54:16.026756 [debug    ] https://raw.githubusercontent.com:443 "GET /raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml HTTP/1.1" 200 171 [urllib3.connectionpool]
room_ensurer_1          | 2021-02-23 03:54:16.031339 [error    ] Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)') [__main__]
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 457, in get_matrix_servers
room_ensurer_1          |     known_servers: Dict[str, List[str]] = json.loads(response.text)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
room_ensurer_1          |     return _default_decoder.decode(s)
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
room_ensurer_1          |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
room_ensurer_1          |   File "/usr/local/lib/python3.7/json/decoder.py", line 355, in raw_decode
room_ensurer_1          |     raise JSONDecodeError("Expecting value", s, err.value) from None
room_ensurer_1          | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
room_ensurer_1          |
room_ensurer_1          | The above exception was the direct cause of the following exception:
room_ensurer_1          |
room_ensurer_1          | Traceback (most recent call last):
room_ensurer_1          |   File "/room_ensurer.py", line 419, in main
room_ensurer_1          |     room_ensurer = RoomEnsurer(username, password, own_server, known_servers_url)
room_ensurer_1          |   File "/room_ensurer.py", line 99, in __init__
room_ensurer_1          |     known_servers_url, server_list_type=ServerListType.ALL_SERVERS
room_ensurer_1          |   File "/opt/venv/lib/python3.7/site-packages/raiden/utils/cli.py", line 464, in get_matrix_servers
room_ensurer_1          |     ) from ex
room_ensurer_1          | RuntimeError: Could not process list of known matrix servers: 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers.alderaan.yaml' => JSONDecodeError('Expecting value: line 1 column 1 (char 0)')</code></pre>

<pre><code>mossimokim@raijin1:~/raiden-service-bundle/data/keystore$ sudo docker-compose logs --tail 100 pfs
Attaching to raiden-service-bundle_pfs_1
pfs_1                   | | Such to the extent as permissible by applicable laws and regulations.  |
pfs_1                   | |                                                                        |
pfs_1                   | | Privacy Warning: Please be aware, that by using the Raiden Pathfinding |
pfs_1                   | | service or Monitoring service among others, your Ethereum address,     |
pfs_1                   | | account balance and your transactions will be stored on the Ethereum   |
pfs_1                   | | chain, i.e. on servers of Ethereum node operators and ergo are to a    |
pfs_1                   | | certain extent publicly available. The same might also be stored on    |
pfs_1                   | | systems of parties running Raiden nodes connected to the same token    |
pfs_1                   | | network. Data present in the Ethereum chain is very unlikely to be     |
pfs_1                   | | able to be changed, removed or deleted from the public arena.          |
pfs_1                   | |                                                                        |
pfs_1                   | | This implementation follows the technical specification of             |
pfs_1                   | | https://raiden-network-specification.readthedocs.io/en/latest/         |
pfs_1                   | | Pathfinding service.                                                   |
pfs_1                   | +------------------------------------------------------------------------+
pfs_1                   |
pfs_1                   | 2021-02-23 03:56:54.983200 [info     ] Using RPC endpoint             [__main__] rpc_url=https://mainnet.infura.io/v3/c6fbbc5360eb4eb49db1791bc94ccdf5
pfs_1                   | 2021-02-23 03:56:54.983797 [info     ] Contract information           [__main__] addresses={'TokenNetworkRegistry': '0x6d07A2ef8De5d7D48337510BCEb9FEEa5424b20c', 'UserDeposit': '0x1c62fF66aF8aaD410065E02338F5bFbbe23e1f10', 'OneToN': '0x960f01E9E219E1c8564784a050fD1cA51651592D'} start_block=10095771
pfs_1                   | 2021-02-23 03:56:55.231361 [info     ] PFS payment address            [pathfinding_service.service] address=0xA4924990BAb23345f5Ab4CA095e3df39955Ddbab
pfs_1                   | 2021-02-23 03:56:55.231963 [info     ] Opening database               [raiden_libs.database] filename=/state/pfs-state.db
pfs_1                   | 2021-02-23 03:56:55.289510 [info     ] Using Matrix server            [raiden.network.transport.matrix.utils] average_rtt=0 server_ident=Synapse/1.22.1 server_url=https://transport.raijin1.raiden.ninja
pfs_1                   | 2021-02-23 03:56:55.290561 [debug    ] Waiting for service to start before accepting API requests [__main__]
pfs_1                   | 2021-02-23 03:56:55.363074 [debug    ] Logged in                      [raiden.network.transport.matrix.utils] homeserver=transport.raijin1.raiden.ninja node=0xA4924990BAb23345f5Ab4CA095e3df39955Ddbab server_url=https://transport.raijin1.raiden.ninja
pfs_1                   | Traceback (most recent call last):
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 588, in join_broadcast_room
pfs_1                   |     room = client.join_room(broadcast_room_alias)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/client.py", line 320, in join_room
pfs_1                   |     response = self.api.join_room(room_id_or_alias)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 195, in join_room
pfs_1                   |     return self._send("POST", path)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 183, in _send
pfs_1                   |     return super()._send(method, path, *args, **kwargs)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
pfs_1                   |     code=response.status_code, content=response.text
pfs_1                   | matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_mainnet_path_finding:transport.raijin1.raiden.ninja not found"}
pfs_1                   |
pfs_1                   | During handling of the above exception, another exception occurred:
pfs_1                   |
pfs_1                   | Traceback (most recent call last):
pfs_1                   |   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
pfs_1                   |   File "/services/src/raiden_libs/matrix.py", line 183, in _run
pfs_1                   |     self._start_client()
pfs_1                   |   File "/services/src/raiden_libs/matrix.py", line 218, in _start_client
pfs_1                   |     client=self._client, broadcast_room_alias=room_alias
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 593, in join_broadcast_room
pfs_1                   |     f"Could not join broadcast room {broadcast_room_alias}. "
pfs_1                   | raiden.exceptions.RaidenUnrecoverableError: Could not join broadcast room #raiden_mainnet_path_finding:transport.raijin1.raiden.ninja. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.
pfs_1                   | 2021-02-23T03:56:55Z <MatrixListener at 0x7f6243986950: _run> failed with RaidenUnrecoverableError
pfs_1                   |
pfs_1                   | 2021-02-23 03:56:55.386629 [info     ] Stopping Pathfinding Service... [__main__]
pfs_1                   | Traceback (most recent call last):
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 588, in join_broadcast_room
pfs_1                   |     room = client.join_room(broadcast_room_alias)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/client.py", line 320, in join_room
pfs_1                   |     response = self.api.join_room(room_id_or_alias)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 195, in join_room
pfs_1                   |     return self._send("POST", path)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/client.py", line 183, in _send
pfs_1                   |     return super()._send(method, path, *args, **kwargs)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
pfs_1                   |     code=response.status_code, content=response.text
pfs_1                   | matrix_client.errors.MatrixRequestError: 404: {"errcode":"M_NOT_FOUND","error":"Room alias #raiden_mainnet_path_finding:transport.raijin1.raiden.ninja not found"}
pfs_1                   |
pfs_1                   | During handling of the above exception, another exception occurred:
pfs_1                   |
pfs_1                   | Traceback (most recent call last):
pfs_1                   |   File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
pfs_1                   |     "__main__", mod_spec)
pfs_1                   |   File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
pfs_1                   |     exec(code, run_globals)
pfs_1                   |   File "/services/src/pathfinding_service/cli.py", line 159, in <module>
pfs_1                   |     main(auto_envvar_prefix="PFS")  # pragma: no cover
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
pfs_1                   |     return self.main(*args, **kwargs)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
pfs_1                   |     rv = self.invoke(ctx)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
pfs_1                   |     return ctx.invoke(self.callback, **ctx.params)
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
pfs_1                   |     return callback(*args, **kwargs)
pfs_1                   |   File "/services/src/raiden_libs/cli.py", line 244, in call_with_blockchain_info
pfs_1                   |     return callback(**params)
pfs_1                   |   File "/services/src/raiden_libs/cli.py", line 169, in call_with_common_options_initialized
pfs_1                   |     return func(**params)
pfs_1                   |   File "/services/src/pathfinding_service/cli.py", line 129, in main
pfs_1                   |     service.startup_finished.get(timeout=PFS_START_TIMEOUT)
pfs_1                   |   File "src/gevent/event.py", line 305, in gevent._gevent_cevent.AsyncResult.get
pfs_1                   |   File "src/gevent/event.py", line 335, in gevent._gevent_cevent.AsyncResult.get
pfs_1                   |   File "src/gevent/event.py", line 323, in gevent._gevent_cevent.AsyncResult.get
pfs_1                   |   File "src/gevent/event.py", line 303, in gevent._gevent_cevent.AsyncResult._raise_exception
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/gevent/_compat.py", line 65, in reraise
pfs_1                   |     raise value.with_traceback(tb)
pfs_1                   |   File "src/gevent/greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
pfs_1                   |   File "/services/src/raiden_libs/matrix.py", line 183, in _run
pfs_1                   |     self._start_client()
pfs_1                   |   File "/services/src/raiden_libs/matrix.py", line 218, in _start_client
pfs_1                   |     client=self._client, broadcast_room_alias=room_alias
pfs_1                   |   File "/usr/local/lib/python3.7/site-packages/raiden/network/transport/matrix/utils.py", line 593, in join_broadcast_room
pfs_1                   |     f"Could not join broadcast room {broadcast_room_alias}. "
pfs_1                   | raiden.exceptions.RaidenUnrecoverableError: Could not join broadcast room #raiden_mainnet_path_finding:transport.raijin1.raiden.ninja. Make sure the Matrix server you're trying to connect to uses the recommended server setup, esp. the server-side broadcast room creation. See https://github.com/raiden-network/raiden-transport.</code></pre>

<pre><code>mossimokim@raijin1:~/raiden-service-bundle/data/keystore$ sudo docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:58 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:52 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0</code></pre>

<pre><code>mossimokim@raijin1:~/raiden-service-bundle/data/keystore$ sudo docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020</code></pre>

<pre><code>mossimokim@raijin1:~/raiden-service-bundle/data/keystore$ uname -srm
Linux 5.4.0-65-generic x86_64</code></pre>

**Comment by ulope** [comment]
@mossimokim Did you by chance uncomment the `URL_KNOWN_FEDERATION_SERVERS` setting in `.env`? The error message looks like that might be the case. If so please delete or re-comment that line please.

**Comment by mossimokim** [comment]
Odd. URL_KNOWN_FEDERATION_SERVERS was clearly commented. However, deleting the line and restarting did the job. pfs is up! Thank you @ulope!
[pfs endpoint](https://pfs.raijin1.raiden.ninja/api/v1/info)

**Comment by ezdac** [comment]
Your server is [now included](https://github.com/raiden-network/raiden-service-bundle/pull/257) in the active whitelist. Congratulations and thank you for support :) 

Closing this issue, feel free to reopen if there are remaining questions.

**Comment by ulope** [comment]
@mossimokim Can you please check the logs of the MS & PFS? The monitoring shows that they aren't up.

**Comment by mossimokim** [comment]
ms show "Your account's balance is below the estimated gas reserve of xxx". I topped it up a bit. What is minimum/recommended amount? PFS did not show any error last 5000 records, but infura show requests went over the free quota of 100k and throttled for about 8 hours per day. Signed up dev account for 200k requests. Hope this fixes up the problem.

**Comment by mossimokim** [comment]
No errors found last 24 hours for both ms and pfs
