### ISSUE TITLE
Add node monitoring to compose stack

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-service-bundle#23]
# Problem Description

We currently only expose monitoring of Synapse and the Traefik proxy. 
To get better insight into the health of the systems we also need to expose node metrics via prometheus' `node_exporter`. 

## Tasks

- [ ] Add `node_exporter` to the docker-compose definition
- [ ] Expose `node_exporter` metrics on a sub-path of the `metrics.<server-name>` vhost

**Comment by fredo** [comment]
can be closed due to duplicate #200
