### ISSUE TITLE
Why is table "event_push_actions" growing so heavily

### ISSUE THREAD

**Issue by karlb** [raiden-network/raiden-service-bundle#236]

**Comment by fredo** [comment]
# Content of `event_push_actions`
After analyzing the table `event_push_actions` I came to the following conclusion about the content. 

Each event which triggers a push notification on a user's device will result in an entry in this table.

My findings show that in our case, only messages in public rooms result in an entry in that table. This is the pathfinding service and monitoring service room. Unfortunately,  this results in massive amounts of entries in this table as every message (i.e. `CapacityUpdate`) results in an entry PER USER in this room. I could see that this only happens for unread messages (i.e. a user being offline).

The table has a column `highlight` and if this flag is 0 the entries should be cleaned up after 24h period. As of now, 99.6% of the messages in the table have `highlight` set to `0` on `transport01`.

# Growth of `event_push_actions`

As written above we experience a database growth with a complexity of `M x N (M = number of messages, N = number of user)`. 

First of all, the "good news". It seems that the database growth leads to the supposingly odd behavior of vacuuming the database. While the `row_estimates` stays on a constant (but high) level, the `size_bytes` value is steadily increasing. I think that the vacuum problem pops up at tables which have large amounts of entries within the interval of synapse's internal database clean up. Imagine having 1_000_000 entries per 24h, assuming that the non-highlighted values get cleaned up every 24h. If table space does not get released properly the database growth is significantly higher than on tables with low traffic.

# Disabling push notifications
Nonetheless, we do not need push notifications at all. Even if we would fix the vacuum problem and the table would have a constant size we could take off some load off of the server if we could disable it.
Unfortunately, it does not seem possible to have a server-wide option to disable push notifications and therefore storing this unnecessary entries in the table. Push notifications are handled by `push rules`. There exist server-default push rules and even one which is disabling all push notifications (`.m.rule.master`). This rule is disabled by default... (note the double negation here)
Enabling this rule (to disable all push notifications) stops putting entries for a particular address. 

Only a user can enable it for himself. Furthermore, all push rules defined by a user override any server-default rule. This means, that from my understanding it is not possible to turn off notifications for a complete server.


# Proposed Solutions
## Turning off push notifications client side
For one we can have a quick solution: A raiden client can disable push notifications completely when starting the transport. IMHO this should definitely be the default. Note, that this does not prevent malicous raiden nodes to spam the table (by turning notifications on again).

## Sending Capacity Updates per toDevice message

This idea also comes hand in hand with the privacy discussion about capacity updates. As we have seen, entries in the table are only created by messages being sent in `public rooms`. This could be avoided by sending messages to the PFSes per `toDevice`. This option would also mean that capacity updates cannot be read anymore from other raiden users in the global pfs room. I also opt for this option but I suggest a discussion about this decision in the team beforehand.

# Questions to Element

Additionally, Element might be able to help on what is possible to configure. My question to Element would be: 

- Is it possible to turn off push notifications for a server regardless what a user configures?
- If yes, how can this be configured?
- Is it a correct behavior that the `.m.rule.master` cannot be enabled by default for all users on the server?

**Comment by karlb** [comment]
@fredo Please ask your open questions in https://app.element.io/#/room/!FdzHexUrDOCMnKyBbL:matrix.org

**Comment by fredo** [comment]
It's not possible to turn off push notifications server side. 

quick solution: 

disable push rules 

> a quick solution for disabling them would be to set BASE_RULE_IDS to the empty set()
> i.e. comment out https://github.com/matrix-org/synapse/blob/master/synapse/push/baserules.py#L573-L591

**Comment by fredo** [comment]
After 2 days with push notifications turned off the result is:

- Size in bytes did not increase for two days (before it was increasing every day)
- Row estimate keeps alternating but on a constant level 

I suggest to close this issue for now but keep observing the behavior of the table for in the next days
