### ISSUE TITLE
Prepare RSB Release / Create RC

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-service-bundle#246]
We need a new release with the latest features / settings.
- [x] Release latest `raiden-services` (depends on https://github.com/raiden-network/raiden-services/pull/909 and https://github.com/raiden-network/raiden-services/pull/912)
- [x] Polish Changelog & Release Notes
- [x] Create RC and run RC on staging
- [ ] Release

**Comment by konradkonrad** [comment]
Staging RC is done and up on `transport0[1-5]`. Full RSB release postponed [until newer communication model client<->services is worked out](https://github.com/raiden-network/raiden/issues/6851).

**Comment by ezdac** [comment]
FIY, this release will fix an issue with the `raiden-services`:

https://github.com/raiden-network/raiden-services/pull/966

**Comment by konradkonrad** [comment]
https://github.com/raiden-network/raiden-service-bundle/issues/265

**Comment by fredo** [comment]
closed in favor of #265
