### ISSUE TITLE
Upgrade to Synapse 1.29

### ISSUE THREAD

**Issue by ulope** [raiden-network/raiden-service-bundle#261]
# Problem Description

With raiden-network/raiden#6876 we upgraded the dev dependencies to Synapse `1.29`.
We need to do the same here.
The [upgrading docs state that reverse proxies must now pass the `X-Forwarded-Proto` header](https://github.com/matrix-org/synapse/blob/v1.29.0/UPGRADE.rst#upgrading-to-v1290). We need to check that this happens with Traefik.

**Comment by fredo** [comment]
already on 1.33.0
