### ISSUE TITLE
Prepare RC for mainnet release

### ISSUE THREAD

**Issue by fredo** [raiden-network/raiden-service-bundle#265]
# Problem Description

We had to change some things to make the presence router work. The bugs will hopefully be fixed soon and we can revert the changes

- [x] point to synapse 1.33.0
- [x] merge the necessary commits from `feature/presence-hook`
- [x] Remove/ refactor room ensurer
- [x] remove/refactor puger script
- [x] implement whitelist update for federation list @ulope link issue (comes after first RC)
- [x] point to the final raiden-services release

**Comment by palango** [comment]
Seems to be done
