### ISSUE TITLE
Monitoring for the Matrix server

### ISSUE THREAD

**Issue by LefterisJP** [raiden-network/raiden-service-bundle#30]
To ensure we have a functioning network and also to gather statistic information about the network (number of messages, channels, etc.) the Raiden Matrix servers need to be monitored. Both on the operating system / server health as well as the Matrix server level itself. 

Synapse (the Matrix homeserver reference implementation) already supports monitoring via Prometheus out of the box and have also had good experiences with it in the past.

We will want to have aggregate monitoring over all (or as many as possible) servers but we also need the server operators themselves to run their own monitoring to be able to quickly react to any possible incidents.

**Comment by fredo** [comment]
closed in favor of age. Monitoring is there and steadily improved by smaller issues
