### ISSUE TITLE
Rename repository to `raiden-service-bundle`

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-service-bundle#34]
# Problem Description
Since we're including https://github.com/raiden-network/raiden-services services in the docker automation, this repository now goes beyond its current title.

- `raiden-network/raiden-services` shall remain a repository of its own.

- if we ever consider it important to have the transport container descriptions separate, too, I suggest to create a new repository for that.

Note, I don't have the necessary admin fu to do this...

Follow up:
- [x] automate container builds and publishing of tagged versions to dockerhub (via CI or dockerhub) #36 
- [x] use only version-tagged dockerhub images in "main" `docker-compose.yaml` #36 
- [x] improve documentation for the complete bundle

**Comment by czepluch** [comment]
Renamed it
