### ISSUE TITLE
Version Bumps should happen tool assisted

### ISSUE THREAD

**Issue by konradkonrad** [raiden-network/raiden-service-bundle#50]
# Problem Description

The third party versions, as well as the version tags for the images that reside in this repository (`build/*`), are scattered across `docker-compose.yaml` and `.circleci/config.yml`. 
We should maintain a central file with all versions, that:
- Allows to quickly see the referenced image version tags.
- Allows for central version maintenance and minimizes the chance for manual errors.

# Proposed Solution
I believe this can be achieved with a [`bumpversion.cfg`](https://github.com/peritus/bumpversion#configuration).

We should maintain:
```
SYNAPSE_VERSION=v1.4.1
RAIDEN_SERVICES_VERSION=stable
RELEASE_GIT_TAG=2019.10.1
```
and configure `bumpversion` to use these to replace all version strings, i.e.:
- `raidennetwork/raiden-services-bundle:${RELEASE_GIT_TAG}_db` etc.
(for description of the versioning-tag scheme for containers, please refer to: https://github.com/raiden-network/raiden-service-bundle/pull/48#issue-339883963).
- `raidennetwork/raiden-services:${RAIDEN_SERVICES_VERSION}`

in 

- `README.md`
- `docker-compose.yaml`
- `.circleci/config.yml`
- `build/synapse/Dockerfile`

when we want to create a new release tag.

**Comment by ulope** [comment]
I tried to do this in the past but unfortunately I wasn't able to prevent bump(2)version from also changing the version numbers in the changelog section in the readme.

Easy solution: split the changelog out of the readme.

**Comment by konradkonrad** [comment]
Thanks @ulope -- I figured out, that I could not get `bump(2)version` to play nicely with multiple different version strings to maintain. Instead I ended up with the solution in #57. 
For the actual version bump, the release version of this repository should still be maintained with bumpversion.
