### ISSUE TITLE
Update the Readme from transport to raiden service bundle

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/raiden-service-bundle#55]
### Problem
Currently, the [Readme](https://github.com/raiden-network/raiden-service-bundle/blob/master/README.md) describes the transport server and doesn't include the whole service bundle.

### Expected Result
The [Readme](https://github.com/raiden-network/raiden-service-bundle/blob/master/README.md) describes the whole service bundle.

**Comment by konradkonrad** [comment]
not sure, if this still applies?
If there is anything missing in particular, please expand on the issue description.

**Comment by christianbrb** [comment]
I have been checking the first paragraphs, which all point to the transport (server). Further down it looked better, but I didn't check it in detail.

# Raiden Transport

## What is this repository

This repository contains the documentation and configuration necessary to run a
Raiden Transport Matrix server.

**Current release:** [2019.11.1](https://github.com/raiden-network/raiden-service-bundle/tree/2019.11.1)

## Table of Contents

[...]

## Overview

The Raiden Network uses a federation of [Matrix](https://matrix.org) servers as its transport
layer. To ensure reliability, availability and neutrality it is desirable that those servers are
being operated by multiple independent entities.

Therefore we provide this repository which allows easy setup of such a transport server.
It uses docker and docker-compose for easy installation and upgrades.

Currently only this single-server configuration is supported; in the future we may also
provide configurations with services split among multiple servers.
