### ISSUE TITLE
Purger service auto updates federation list

### ISSUE THREAD

**Issue by eorituz** [raiden-network/raiden-service-bundle#70]
# Problem Description
When creating an isolated environment we don't want our RSB to connect to other Matrix servers/PFS/MS.
@ulope mentioned that we would need to disable the purger service "since that apart from clearing out room history also updates the federation whitelist". 

# Solution
I'd need the purger service that doesn't update the federation whitelist but stays with the empty one that I provided initially

**Comment by ulope** [comment]
If you set the federation whitelist url in `.env` to an empty file. It will do the right thing.

There was a bug in previous versions of synapse that caused an empty whitelist to behave as if no restriction was set, but that’s since been fixed.
